// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"30","screenWidth":"960","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"DTextPicture","status":true,"description":"동적 문자열 픽쳐 생성 플러그인","parameters":{"itemIconSwitchId":"0","lineSpacingVariableId":"0","frameWindowSkin":"","frameWindowPadding":"18","padCharacter":"0","prefixText":""}},
{"name":"FixImageLoading","status":true,"description":"","parameters":{}},
{"name":"Sinacs_VarSwiSetting","status":true,"description":"변수 및 스위치 호출 및 세팅의 구문을 줄여서 쓸 수 있게 해줌","parameters":{"파라미터 없음":""}}
];
